### ISSUE TITLE
Call to useRouter outside of the sutup function

### ISSUE THREAD

**Issue by fessacchiotto** [yisibell/vue-composition-wrapper#2]
Hi! How can I use a call to useRouter for example, outside of the sutup function?
I'm using a project with Vue 2.6.
Thank you

**Comment by yisibell** [comment]
> Hi! How can I use a call to useRouter for example, outside of the sutup function? I'm using a project with Vue 2.6. Thank you

**Composite APIs** can only run in the `setup` function.

**Comment by fessacchiotto** [comment]
Thank you. On 23 Apr 2024, at 03:17, Yisibell Hong ***@***.***> wrote:﻿

Hi! How can I use a call to useRouter for example, outside of the sutup function? I'm using a project with Vue 2.6. Thank you

Composite APIs can only run in the setup function.
